import React from 'react'
import '../personajes/personajesStyle/personajes.css';
import { GiSpiderWeb } from 'react-icons/gi';
import { FaArrowLeft } from 'react-icons/fa';
import { FaArrowRight } from 'react-icons/fa';

export const MrNegativo = ({
    id = 'MrNegativo',
    personaje = 'Mr. Negativo',
    realName = 'Martin Li',
    bornArea = 'Ciudad de Nueva York, Estados Unidos; antiguamente Fujian, China',
    first_appearance = 'Free Comic Book Day: The Amazing Spider-Man #1 (mayo de 2007)',
    cause = 'Experimentó con una droga sintética creada por el químico de Maggia',
    powers = 'La Fuerza oscura y Fuerza luz le otorga: Fuerza sobrehumana y reflejos, toque sanado, control menta, acceso a tecnología avanzada y laboratorios secretos, posibilidad de cambiar entre apariencia invertida y normal, carga de armas cuerpo a cuerpo con su energía.',
    adds = 'Antes de su transformación, Martin Li era un miembro de la banda de cabeza de serpiente, cuyo verdadero nombre aún no ha sido revelado.',
    creators = 'Dan Slott y Phil Jiménez',
    alias = 'Mr Negativo'
}) => {
const imagePath= `/assets/personajes/${id}.png`;
return (
    <div className='wrappPerson'>
    <div className='personWrap1'>
         <div className='imgWrap'>
            <img src={imagePath} className='card-imgIndividual' alt='Duende Verde'/>
            <div className='dataControlSmall'>
                <ul className='listDataControl'>
                    <li className='listData'>Nombre: <span className='styleData'>{ realName }</span></li>
                    <li className='listData'>Lugar de Nacimiento: <span className='styleData'>{ bornArea }</span></li>
                    <li className='listData'>Causa de sus poderes: <span className='styleData'>{ cause }</span></li>
                    <li className='listData'>Poderes: <span className='styleData'>{ powers }</span></li>
                    <li className='listData'>Añadidos: <span className='styleData'>{ adds }</span></li>
                    <li className='listData'> Primera aparición: <span className='styleData'>{ first_appearance }</span></li>
                    <li className='listData'>Creadores: <span className='styleData'>{ creators }</span></li>
                    <li className='listData'>Alias: <span className='styleData'>{ alias }</span></li>
                </ul>
            </div>
            <div className='buttonNavContainer d-none d-sm-block'>
                <a href="/villanos"><button className='buttonNavigationSpiders'> <GiSpiderWeb/> Ir a Villanos</button></a>
            </div>

        </div>
         <div className='dataWrap'>
            <div className='dataControl'>
                <h3 className='titlePerson'>{ personaje }</h3>
                <div className='infoPersonWrap'>
                    <div className='infoPerson'>
                        <p>El Señor Negativo (Martin Li) es un supervillano Chino que aparece en los cómics estadounidenses publicados por Marvel Comics, generalmente como un enemigo de Spider-Man, Punisher y Cloak y Dagger. El personaje fue creado por Dan Slott y Phil Jimenez, y apareció por primera vez en "Swing Shift", una historia en Free Comic Book Day: The Amazing Spider-Man # 1 (mayo de 2007). El nombre "Señor Negativo" es una referencia al negativo fotográfico, ya que los colores de su piel, cabello y vestuario se invierten cuando cambia entre su yo habitual y su alter ego.</p>
                        <p>Originalmente un gánster chino y traficante de personas, cuyo nombre nunca fue revelado (el nombre Martin Li fue tomado de un esclavo en su barco que murió cuando el barco se estrelló en las costas de Nueva York), el hombre que se convertiría en Señor Negativo ganó sus poderes después siendo capturado por el jefe del crimen Silvermane y experimentado con una droga sintética creada por Simon Marshall (que también le dio a Cloak y Dagger sus poderes). Mientras lograba escapar, los efectos de la droga hicieron que desarrollara dos personalidades opuestas: Martin Li es retratado como un filántropo benevolente y amable, que fundó el Proyecto F.E.A.S.T. como un medio para ayudar a las personas sin hogar, mientras que Sr. Negativo es un notorio jefe del crimen y líder de la pandilla Inner Demons que tiene como objetivo tomar el control del inframundo criminal de Nueva York. Originalmente, el personaje fue representado como sufriendo un trastorno de personalidad múltiple, ya que no mantendría los recuerdos de su alter ego y viceversa, pero luego se demostró que ambos personajes eran plenamente conscientes de la existencia del otro. Como Sr. Negativo, sus poderes incluyen curar, controlar la mente de otros a través de la "corrupción" y cargar armas normales con su energía.</p>
                        <p>El personaje ha aparecido en varias formas de medios, incluidas series animadas y videojuegos.</p> 
                        <p>Martin Li es un inmigrante chino ilegal procedente de la provincia de Fujian, que intentaba viajar a Estados Unidos para estar con su esposa. Sin embargo, su modo de transporte, el oro de la montaña, era un barco de esclavos operado por la banda de cabeza de serpiente como una forma de vender cautivos como esclavos Fujian, destinados en Kenia. Durante una tormenta, la tripulación abandonó el barco, dejando solos a los cautivos. Li fue el único superviviente y pasó los años siguientes la haciéndose con una gran fortuna y dedicándose a ayudar a los menos afortunados.</p>
                        <p>Sin embargo, esta historia resultó ser algo falso, aunque solo el personaje Sr. negativo parece consciente de ello. Se puso de manifiesto que el Señor Negativo era en realidad uno de los miembros de la tripulación de la montaña de oro y cuando el barco casi se estrelló en las costas de Nueva York, que robó la identidad de uno de los esclavos Fujian fallecidos, el verdadero Martin Li, que se dirigía a América, por las razones antes mencionadas. Este miembro de la banda fue capturado por la Maggia, Don Silvermane y experimentó con una droga sintética creada por el químico de Maggia, Simon Marshall, que podría ser más potente que la heroína. Se escapó con la ayuda de otros dos internos y pronto se transformó en dos hombres, el de buen corazón, Martin Li y el malvado Señor Negativo. El lado del Señor Negativo se dedicó a convertirse en eje central del crimen de Chinatown, mientras que el lado de Martin Li intenta ejecutar el centro de ayuda social FEAST con humildad.</p>
                        <p>Martin Li opera un comedor de beneficencia en Chinatown, el Proyecto FEAST (Alimentos, Ayuda de Emergencia, Vivienda y Formación), donde la Tía May de Peter Parker es voluntaria. Ni Peter ni May son conscientes de la doble identidad de Li como un jefe del crimen de Chinatown bajo el nombre de Señor Negativo. A pesar de ser un señor del crimen, Li es un hombre aparentemente amable y generoso. El Proyecto FEAST ha mostrado poderes curativos para las personas de diversas enfermedades, aunque la causa de esta curación todavía no se ha revelado.</p>
                        <p>Durante la primera historia de " Brand New Day", Señor Negativo primero entra en conflicto con Spider-Man cuando se hace un juego de poder hacia la toma de control de Nueva York, tratando de eliminar a todos los miembros existentes de la Karnelli y Maggia, las familias del crimen utilizando un ADN específico de arma biológica llamada el "Aliento del Diablo". A cambio de dejar a los niños vivos de las familias de Maggia, se toma una muestra de sangre de Spider-Man para usar en la fórmula de la respiración de un diablo. El Señor Negativo después intenta utilizar la fórmula Aliento del Diablo para matar a Spider-Man durante una pelea con Maggia, pero Spider-Man es capaz de contener la respiración el tiempo suficiente para escapar con vida. ​Spider-Man, se moviliza con la Gata Negra para ayudarle a robar su sangre restante a partir del Señor Negativo y reemplazarlo con un frasco de sangre de cerdo por lo que el Señor Negativo es consciente de su pérdida.</p>
                        <p>Martin Li respalda a Bill Hollister a la alcaldía de la ciudad de Nueva York, poniéndolo en contra de Randall Crowne, que lo ha añadido a una lista de oponentes (muchos de los cuales se convierten en blancos de la villana, Amenaza, que es en realidad la hija de Hollister, Lilly). También le hace convertirse en el blanco de una campaña de difamación por Dexter Bennet, editor de El DB y partidario de Crowne.8​Después de que Amenaza se revela como la hija de Billy Hollister, Lily y por dimisión como alcalde, Li se ejecuta sin éxito en una elección especial, perdiendo a J. Jonah Jameson.</p>
                        <p>Señor Negativo más tarde recluta a Hammerhead y hace ofertas para poner su cerebro en un nuevo esqueleto de adamantium robótico después de haber sido a quemarropa disparado en la cabeza por el mundo terrenal. Hammerhead está de acuerdo en que el Señor Negativo tiene su cirujano, el doctor Tramma de realizar el procedimiento.</p>
                        <p>Señor Negativo finalmente se encuentra con Eddie Brock y le da un trabajo en su comedor. Un toque de él hace que sus células cancerosas desaparezcan por completo. Además, los restos de la mecha del simbionte Venom, con las células blancas de la sangre de Brock, haciendo que el Anti-Venom está durante un conflicto con Mac Gargan, el anfitrión del simbionte Venom. Después de que el centro de FEAST se desgarra durante la pelea entre los dos, Li descubre a partir de un grupo de trabajadores explotados (en una tienda propiedad de Crowne) que se experimentó con drogas de Oscorp. Más tarde, el Señor Negativo y su encuentro con sus demonios internos y la batalla de Anti-Venom. En la secuela, Brock gira en reloj con Negativo en Li, convirtiéndose en el primero en ser consciente de su doble identidad.</p>
                        <p>Durante la historia del "Dark Reign" 2008-2009, Señor Negativo se niega a someterse a la regla de conquista del inframundo criminal de Nueva York de Capucha. Durante una reunión con el secuaz de Capucha, Dragón Blanco, Señor Negativo corrompe a Dragón Blanco y lo envía a atacar las oficinas centrales de Capucha. En represalia, Capucha decide atacarlo y matarlo. H.A.M.M.E.R. sella a Chinatown en nombre de Capucha y estalló una pelea en toda la finca de Li. La pandilla de Capucha gana la partida hasta que Spider-Man llega para rescatar a Martin. Sin embargo, Spider-Man también está corrupto y enviado a la batalla en nombre de Señor Negativo. Spider-Man ataca y aporrea a los miembros de la pandilla de Capucha que están atacando las oficinas centrales del villano y Señor Negativo luego envía al lanzaredes para matar a Betty Brant que está entrevistando a la viuda real de Martin Li y se está acercando a la verdad. El propio Capucha se enfrenta a Señor Negativo en la sede de Chinatown y lo enfrenta. Durante la batalla, Señor Negativo intenta corromper a Capucha pero falla. Norman Osborn finaliza el bloqueo que H.A.M.M.E.R. tiene en Chinatown cuando Hammerhead entrega documentos que implican a Oscorp en las pruebas de drogas antes mencionadas sobre inmigrantes. Un Furioso Capucha decide matar al Señor Negativo de todos modos, pero se escapa. Una conversación posterior que Osborn tiene con su lado más oscuro Duende Verde revela que ahora tiene una alianza con un Señor Negativo similar a la de Capucha. Sin embargo, La Mancha se desliza y recupera la evidencia de las pruebas de Oscorp, revelando ser el topo de Señor Negativo en la pandilla de Capucha bajo la promesa de que se curará una vez que se vengan de la Maggia.</p>
                        <p>En un principio parece que Martin Li no tiene conocimiento de su lado malo. Durante "Nuevas formas de morir", Li tomó a Eddie Brock en una habitación trasera que él llama su santuario interior, donde afirma que jugar un juego de Go, día a día contra un oponente desconocido que nunca ha visto, afirmando que "ha aprendido que está bien para disfrutar del juego". Cuando se transforma en Sr. Negativo, la apariencia de Li se asemeja a la de un negativo fotográfico. También habla en una burbuja de texto en color inverso, aunque no está claro lo que (si acaso) indica todo esto sobre el sonido de su voz.</p>
                        <p>Antes de su transformación, Martin Li era un miembro de la banda de cabeza de serpiente, cuyo verdadero nombre aún no ha sido revelado. Tanto los personajes, Martin Li y Sr. Negativo son el resultado de las pruebas de drogas experimentales realizados por el químico, Maggia Simon Marshall, las mismas pruebas que alimentaba de Cloak y Dagger (es decir, la asociación de Cloak con la Fuerza Oscura). Sin embargo, a diferencia de los dos héroes, que cada uno se les dio un poder sobre la luz y la oscuridad, el miembro de la banda se le dio tanto una luz y un lado oscuro. Como tal, el Sr. Negativo considera a sí mismo una forma de realización de negro y de maldad y sus dos personajes ven el equilibrio entre el bien y el mal como una parte necesaria del universo. ​Las dos mitades, mientras que plenamente consciente de una sola existencia de otro, toman ninguna medida para interfieren entre sí, con el personaje de Martin Li incluso tomar tales medidas drásticas como permitir su lado malo para corromper a May Parker para mantenerlo en secreto.</p>
                        <p>Durante un encuentro en The Amazing Spider-Man # 621, el Sr. Negativo muestra un grado de fuerza sobrehumana lo suficientemente alto como para enviar a Spider-Man volando a través de dos edificios de un solo golpe. El Sr. Negativo también demuestra reflejos sobrehumanos durante su batalla con Hood, esquivando balas o cortándolas por la mitad con su espada. También tiene el poder para cargar cuchillos y espadas con energía eléctrica negra, y puede corromper a las personas que toca de la misma manera, poniéndolos bajo su control. Las ropas de una persona corrupta cambian sus colores a sus negativos fotográficos, y todos los que están corruptos alaban a su nuevo amo con proclamaciones como "El señor negativo nunca nació, por lo que siempre está vivo", o "No está apegado a nada, así es uno con todos". Se demostró que su corrupción es más efectiva cuanto más buena era la persona afectada antes de su conversión: Dragón Blanco, un villano en persona, obtuvo resistencia y resistencia enormemente aumentadas, pero aun así fue enviado fácilmente (su ropa volvió a la normalidad una vez que fue asesinado). Por el contrario, Spider-Man, un héroe en todos los aspectos, fue corrompido en un malvado y rencoroso villano, despreciando todos los valores que apreciaba (incluso la memoria de su tío Ben ) y nada más que matar.</p>
                        <p>Spider-Man es capaz de romper el control que su lado malévolo tiene sobre él cuando está a punto de matar a Betty Brant, ya que recuerda el amor que una vez tuvo por ella al acercarse. El toque corruptor del Sr. Negativo parece ser ineficaz contra seres con poderes sobrenaturales, ya que Capucha no se ve afectado cuando el Negativo intenta corromperlo; El Sr. Negativo afirma que esto se debe a que el alma de Capucha pertenece a un ser aún más oscuro que él. Desde entonces se ha revelado que aunque Negativo puede renovar su influencia en otros, no puede corromper a alguien una vez que se ha liberado de su influencia, permitiendo que Peter Parker se infiltre en su plan al usar el hecho de que había sido corrompido por Negativo como Spider-Man sin que su enemigo sepa su identidad secreta.</p>
                        <p>El personaje alterno de Martin Li del Sr. Negativo parece tener el poder de curar a los demás: en The Amazing Spider-Man # 568, un simple toque de Li cura completamente a Eddie Brock de su cáncer, y combina los restos del simbionte Venom en su sangre con sus glóbulos blancos, creando un nuevo simbionte llamado Anti-Venom que posee poderes curativos similares. Aparte de esto, las personas sin hogar que se han quedado en el refugio de Martin Li se han recuperado rápidamente de cualquier enfermedad o lesión que sufrieron. Es posible que su toque de curación supuestamente sea lo opuesto al toque corruptor del Sr. Negativo. Se revela que Anti-Venom puede verse afectado por la energía del Sr. Negativo porque niega su capacidad de curación.</p>
                        <p>El Sr. Negativo también tiene acceso a tecnología avanzada y laboratorios secretos, en los que puede brindar a sus pacientes atención médica mucho más avanzada que la disponible para el público en general.</p>
                        <p>En el videojuego: 'Marvel's Spider-Man', Sr. Negativo también posee la capacidad de proyectar potentes descargas eléctricas de energía negativa de sus manos.</p>
                    </div>
                </div>
                <div className='buttonNavContainer d-block d-sm-none'>
                    <a href="/villanos"><button className='buttonNavigationSpiders'> <GiSpiderWeb/> Ir a Villanos</button></a>
                </div>
                <div className='navegationPerson'> 
                    <a href="/personaje/Kraven"><button className='buttonNavigation'><FaArrowLeft/> Kraven</button></a>
                    <br/>
                    <a href="/personaje/Shocker"><button className='buttonNavigation'>Shocker <FaArrowRight/></button></a>
                </div>
            </div>
        </div>
        </div>
    </div>
  )
}
